#!/usr/bin/env node

const program = require('commander');
const pkg = require('./package.json');

program
  .version(pkg.version)
  .command('build', 'build your blog', { isDefault: true })
  .parse(require('process').argv);
